conky.config = {
    alignment = 'middle_middle',
    background = false,
    border_width = 0,
    cpu_avg_samples = 2,
    default_color = '202020',
    double_buffer = true,
    draw_borders = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans:size=10',
    gap_x = 0,
    gap_y = 0,
    minimum_width = 500,
    maximum_width = 500,
    minimum_height = 310,
    maximum_height = 310,
    own_window = true,
    own_window_class = 'ConkyStudy',
    own_window_title = '30-Day Study Dashboard',
    own_window_type = 'normal',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager',
    update_interval = 1,
    use_xft = true,
    xinerama_head = 0,
};

conky.text = [[
${image $HOME/.config/conky-study/card_small.png -p 0,0 -s 500x310}
${execpi 1 python3 "$HOME/.config/conky-study/study_schedule.py"}
]]
